baseURL = "https://lucasdbrown.github.io/"
title = "Lucas Brown — Cybersecurity Blog"
theme = "blowfish"
languageCode = "en-us"

# Enable syntax highlighting for code blocks
[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = true

# Enable menus and social links
[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

# Author information
[author]
  name = "Lucas Brown"
  email = ""
  bio = "RIT Junior Cybersecurity Major passionate about malware analysis, APT campaigns, and OT Security"
  avatar = "/profile.jpg"

# Author parameters for theme
[params.author]
  name = "Lucas Brown"
  image = "profile.jpg"
  headline = "RIT Junior Cybersecurity Major"

# Social links
[[params.social]]
  name = "GitHub"
  url = "https://github.com/lucasdbrown"
  icon = "github"

[[params.social]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/lucas-d-brown/"
  icon = "linkedin"
